apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
  namespace: argocd
spec:
  project: cluster-prod
  source:
    repoURL: https://github.com/DarkSpider90/test_infrazero_gitops
    targetRevision: main
    path: charts/app
    helm:
      valueFiles:
        - ../../config/apps/testapp.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
