apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-secretproviderclass
  namespace: argocd
spec:
  project: cluster-prod
  source:
    repoURL: https://github.com/DarkSpider90/test_infrazero_gitops
    targetRevision: main
    path: platform/infisical
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
